language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.1.5
  - 2.2.2
  - jruby
before_install:
<<<<<<< HEAD
  - gem update --system
  - gem --version
  - gem update bundler
=======
- brew update
- brew upgrade openssl
>>>>>>> 9baa6677a4fbc15667ea0246592dd68672e1cf61
